/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rmv_jni_FordFulkersonJNI */

#ifndef _Included_com_rmv_jni_FordFulkersonJNI
#define _Included_com_rmv_jni_FordFulkersonJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rmv_jni_FordFulkersonJNI
 * Method:    fordFulkerson
 * Signature: ([[III)Ljava/lang/Integer;
 */
JNIEXPORT jint JNICALL Java_com_rmv_jni_FordFulkersonJNI_fordFulkerson
  (JNIEnv *, jobject, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
